compile:
	clang src/my_string.c src/program3.c -o program3;
	wait;
	
	
program3_test:
	./program3 1 abc 2 test 2>&1 > program3_output.txt;
	mv program3_output.txt src/;
	
	
program3_test:
	./program3 1 abc 2 test;
	wait;
	
